when@dev:
    web_profiler:
        toolbar:
            enabled: true
            ajax_replace: true

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler: { collect: false }
